MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: ''
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'efficientnet_b4'
  DEVICE_ID: ('1')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 0.1
  TRIPLET_LOSS_WEIGHT: 0.9
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True

INPUT:
  SIZE_TRAIN: [256,128] #[384, 192]
  SIZE_TEST: [256,128] #[256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('../NAIC_Person_Reid/reid_baseline/dataset/')
  HARD_AUG: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 2

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  MAX_EPOCHS: 50
  BASE_LR: 0.006
  IMS_PER_BATCH: 128
  STEPS: [25,40] #25,40
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 2000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.0003
  FP16: False
TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  WEIGHT: '../model/1229-efn-nocj/efficientnet_b4_45.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
OUTPUT_DIR: "../model/1229-efn-nocj/"

