MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './resnext101_ibn_a-6ace051d.pth'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'resnext101_ibn_a'
  DEVICE_ID: ('0,1')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 0.1
  TRIPLET_LOSS_WEIGHT: 0.9
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True
  USE_SESTN: False
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('../NAIC_Person_Reid/reid_baseline/dataset/')
  HARD_AUG: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  MAX_EPOCHS: 120
  BASE_LR: 0.006
  IMS_PER_BATCH: 160
  STEPS: [40,70] #25,40
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: True
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 50
  EVAL_PERIOD: 2000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.0003
  FP16: False
TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  WEIGHT:  '../model/resnext-a-noCJ-pk4bs224-LFL-readimg/resnext101_ibn_a_120.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
OUTPUT_DIR: "../model/resnext-a-noCJ-pk4bs224-LFL-readimg/"



